from __future__ import annotations

from collections.abc import Mapping


Polynomial = Mapping[tuple[int, ...], float]


def _active_degrees(
    coefficients: Polynomial,
    *,
    coefficient_atol: float,
) -> list[int]:
    if not coefficients:
        raise ValueError("coefficients must be non-empty")
    lengths = {len(exponent) for exponent in coefficients}
    if len(lengths) != 1 or next(iter(lengths)) < 1:
        raise ValueError("all exponent tuples must have the same positive length")
    if coefficient_atol < 0.0:
        raise ValueError("coefficient_atol must be non-negative")

    degrees: list[int] = []
    for exponent, coefficient in coefficients.items():
        if any(power < 0 for power in exponent):
            raise ValueError("exponents must be non-negative")
        degree = sum(exponent)
        if degree > 0 and abs(float(coefficient)) > coefficient_atol:
            degrees.append(degree)
    return degrees


def rescaled_gradient_flow_loss_coefficients(
    coefficients: Polynomial,
    scale: float,
    *,
    leading_degree: int | None = None,
    coefficient_atol: float = 0.0,
) -> dict[tuple[int, ...], float]:
    """Loss coefficients in the natural local gradient-flow scaling.

    Write ``x = delta*y`` and let ``d`` be the first nonconstant loss degree.
    Under the natural local time change ``t = delta**(2-d) * s``, the rescaled
    gradient flow is generated by the nonconstant polynomial

        sum_alpha c_alpha * delta**(|alpha|-d) * y**alpha.

    Thus degree-``d`` support remains order one while a degree-``p`` correction
    enters at order ``delta**(p-d)``. Constant terms are omitted because they do
    not affect gradient flow.
    """
    delta = float(scale)
    if delta <= 0.0:
        raise ValueError("scale must be positive")
    atol = float(coefficient_atol)
    degrees = _active_degrees(coefficients, coefficient_atol=atol)
    if not degrees:
        return {}

    if leading_degree is None:
        d = min(degrees)
    else:
        d = int(leading_degree)
        if d <= 0:
            raise ValueError("leading_degree must be positive")
        if any(degree < d for degree in degrees):
            raise ValueError("leading_degree exceeds active lower-degree support")

    return {
        tuple(int(power) for power in exponent): float(coefficient)
        * delta ** (sum(exponent) - d)
        for exponent, coefficient in coefficients.items()
        if sum(exponent) > 0 and abs(float(coefficient)) > atol
    }


def near_tie_margin_exponent(
    leading_degree: int,
    correction_degree: int,
) -> int:
    """Initialization exponent of the route-selection near-tie window.

    If degree ``d`` determines the leading route competition and the first
    correction that can alter that competition has degree ``p>d``, then after
    local rescaling the correction is order ``delta**(p-d)``. A leading route
    advantage of the same order is therefore not uniformly protected from
    reversal by higher-order terms.
    """
    d = int(leading_degree)
    p = int(correction_degree)
    if d <= 0:
        raise ValueError("leading_degree must be positive")
    if p <= d:
        raise ValueError("correction_degree must exceed leading_degree")
    return p - d
